# Generated by Django 4.0.3 on 2022-03-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=254)),
                ('balance', models.IntegerField()),
                ('type_card', models.CharField(max_length=20)),
                ('currency_type', models.CharField(max_length=50)),
            ],
        ),
    ]
